package imageembedder;

import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JDialog;
import javax.swing.JFrame;
import types.Card;
import types.EmbedType;
import types.UnitType;

public abstract class ImageEmbedderConsole extends javax.swing.JPanel {

    private Console console;
    private final EmbedderInfo embedderInfo;
    private final Card card;
    private final JDialog cardDialog;
    private JFrame frame;
    private final Dimension CARD_DIALOG_SIZE = new Dimension(550, 500);

    public ImageEmbedderConsole(JFrame frame, EmbedderInfo embedderInfo) {
        this.frame = frame;
        this.embedderInfo = embedderInfo;
        {  // creating dialog to use single Card every time.
            card = new Card() {
                @Override
                public void createCard() {
                    embedderInfo.addEmbed(getEmbedtype());
                    console.resetCards();
                    cardDialog.dispose();
                    updateUI();
                }

                @Override
                public void cancelCard() {
                    cardDialog.dispose();
                }

                @Override
                public void editCard() {
                    console.resetCard(card.getEmbedtype());
                    console.resetCards();
                    cardDialog.dispose();
                    updateUI();
                }
            };
            cardDialog = new JDialog();
            cardDialog.setTitle("Image Embedder");
            cardDialog.setModal(true);

            cardDialog.add(card);
            cardDialog.setResizable(false);
        }
        initComponents();
        console = ((ConsoleHolder) consolePane).getConsole();
    }

    public EmbedderInfo getEmbedderInfo() {
        return embedderInfo;
    }

    private void addCard() {
        card.reset();
        card.createOrEdit = card.CREATE;
        Dimension dim = CARD_DIALOG_SIZE;
        Rectangle cb = frame.getBounds();
        cardDialog.setSize(CARD_DIALOG_SIZE);
        cardDialog.setLocation(cb.x + (cb.width - dim.width)
                / 2, cb.y + (cb.height - dim.height) / 2);
        cardDialog.setVisible(true);
    }

    private void editCard() {
        EmbedType et = console.getSelectedEmbedType();
        if (et != null) {
            card.resetFromEmbedType(et);
            card.createOrEdit = card.EDIT;
            Dimension dim = CARD_DIALOG_SIZE;
            Rectangle cb = frame.getBounds();
            cardDialog.setSize(CARD_DIALOG_SIZE);
            cardDialog.setLocation(cb.x + (cb.width - dim.width)
                    / 2, cb.y + (cb.height - dim.height) / 2);
            cardDialog.setVisible(true);
        }
    }

    private void nextCard() {
        console.selectNextCard();
    }

    private void prevCard() {
        console.selectPrevCard();
    }

    private void removeCard() {
        embedderInfo.removeEmbed(console.getSelectedEmbedType());
        console.resetCards();
    }

    private String getPosUnitType() {
        return positionUnitCombo.getSelectedIndex() == 0 ? "%" : "px";
    }

    private void locationChanged(int x, int y) {
        posXField.setText(Integer.toString(x));
        posYField.setText(Integer.toString(y));
    }

    abstract void applyChanges();

    abstract void updateWallpapers();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consolePane = new ConsoleHolder(embedderInfo){
            @Override
            public void locationChanged(int x, int y){
                ImageEmbedderConsole.this.locationChanged(x, y);
            }
        };
        positionUnitCombo = new javax.swing.JComboBox();
        addCardButton = new javax.swing.JButton();
        removeCardButton = new javax.swing.JButton();
        posXLabel = new javax.swing.JLabel();
        posXField = new javax.swing.JFormattedTextField();
        posXTypeLabel = new javax.swing.JLabel();
        posYLabel = new javax.swing.JLabel();
        posYField = new javax.swing.JFormattedTextField();
        posYTypeLabel = new javax.swing.JLabel();
        editCardButton = new javax.swing.JButton();
        nextCardButton = new javax.swing.JButton();
        prevCardButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        applyButton1 = new javax.swing.JButton();
        updateTimer = new javax.swing.JFormattedTextField();
        posYLabel1 = new javax.swing.JLabel();
        posYTypeLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout consolePaneLayout = new javax.swing.GroupLayout(consolePane);
        consolePane.setLayout(consolePaneLayout);
        consolePaneLayout.setHorizontalGroup(
            consolePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        consolePaneLayout.setVerticalGroup(
            consolePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        positionUnitCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "%", "px" }));
        positionUnitCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionUnitComboActionPerformed(evt);
            }
        });

        addCardButton.setText("Add Card");
        addCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardButtonActionPerformed(evt);
            }
        });

        removeCardButton.setText("Remove Card");
        removeCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCardButtonActionPerformed(evt);
            }
        });

        posXLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        posXLabel.setText("Position X  : ");

        posXField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        posXField.setText("0");
        posXField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                posXFieldPropertyChange(evt);
            }
        });

        posXTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posXTypeLabel.setText(getPosUnitType());
        posXTypeLabel.setAlignmentX(0.5F);

        posYLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        posYLabel.setText("Position Y  : ");

        posYField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        posYField.setText("0");
        posYField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                posYFieldPropertyChange(evt);
            }
        });

        posYTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posYTypeLabel.setText(getPosUnitType());
        posYTypeLabel.setAlignmentX(0.5F);

        editCardButton.setText("Edit Card");
        editCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCardButtonActionPerformed(evt);
            }
        });

        nextCardButton.setText("Next Card");
        nextCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardButtonActionPerformed(evt);
            }
        });

        prevCardButton.setText("Prev Card");
        prevCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevCardButtonActionPerformed(evt);
            }
        });

        applyButton.setText("Save ");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        applyButton1.setText("Update Walls");
        applyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButton1ActionPerformed(evt);
            }
        });

        updateTimer.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        updateTimer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                updateTimerPropertyChange(evt);
            }
        });

        posYLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        posYLabel1.setText("Update Timer : ");

        posYTypeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        posYTypeLabel1.setText("min");
        posYTypeLabel1.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consolePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(editCardButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prevCardButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextCardButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addCardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeCardButton, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(applyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(posXLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posXField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(posXTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(posYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posYField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(posYTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(positionUnitCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(posYLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posYTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prevCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(consolePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(posYLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posYTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(posXLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posXField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posYField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posYTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(posXTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(positionUnitCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardButtonActionPerformed
        addCard();
    }//GEN-LAST:event_addCardButtonActionPerformed

    private void positionUnitComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionUnitComboActionPerformed
        console.resetLocationUnitType(UnitType.parseSign(getPosUnitType()));
        posXTypeLabel.setText(getPosUnitType());
        posYTypeLabel.setText(getPosUnitType());
    }//GEN-LAST:event_positionUnitComboActionPerformed

    private void posYFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_posYFieldPropertyChange
        if (evt.getPropertyName().equals("value")) {
            console.resetLocationY(Integer.parseInt(evt.getNewValue().toString()));
        }
    }//GEN-LAST:event_posYFieldPropertyChange

    private void posXFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_posXFieldPropertyChange
        if (evt.getPropertyName().equals("value")) {
            console.resetLocationX(Integer.parseInt(evt.getNewValue().toString()));
        }
    }//GEN-LAST:event_posXFieldPropertyChange

    private void editCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCardButtonActionPerformed
        editCard();
    }//GEN-LAST:event_editCardButtonActionPerformed

    private void nextCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardButtonActionPerformed
        nextCard();
    }//GEN-LAST:event_nextCardButtonActionPerformed

    private void prevCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevCardButtonActionPerformed
        prevCard();
    }//GEN-LAST:event_prevCardButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        applyChanges();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void removeCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCardButtonActionPerformed
        removeCard();
    }//GEN-LAST:event_removeCardButtonActionPerformed

    private void applyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButton1ActionPerformed
        updateWallpapers();
    }//GEN-LAST:event_applyButton1ActionPerformed

    private void updateTimerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_updateTimerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTimerPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCardButton;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton applyButton1;
    private javax.swing.JPanel consolePane;
    private javax.swing.JButton editCardButton;
    private javax.swing.JButton nextCardButton;
    private javax.swing.JFormattedTextField posXField;
    private javax.swing.JLabel posXLabel;
    private javax.swing.JLabel posXTypeLabel;
    private javax.swing.JFormattedTextField posYField;
    private javax.swing.JLabel posYLabel;
    private javax.swing.JLabel posYLabel1;
    private javax.swing.JLabel posYTypeLabel;
    private javax.swing.JLabel posYTypeLabel1;
    private javax.swing.JComboBox positionUnitCombo;
    private javax.swing.JButton prevCardButton;
    private javax.swing.JButton removeCardButton;
    private javax.swing.JFormattedTextField updateTimer;
    // End of variables declaration//GEN-END:variables
}
