/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imageembedder_WinSettings */

#ifndef _Included_imageembedder_WinSettings
#define _Included_imageembedder_WinSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imageembedder_WinSettings
 * Method:    broadcastChange
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imageembedder_WinSettings_broadcastChange
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
